"""Core data models for the enterprise simulation harness.

No hardcoded domains. ``SimEnvironment`` is entirely LLM-generated from
a plain-text context description.  Every field is a data structure — no
domain-specific logic lives here.

Persistence: datasets are stored as JSONL.
  Line 0  — DatasetMetadata  (includes the serialized SimEnvironment)
  Lines 1+ — Scenario
"""

from __future__ import annotations

import statistics
import time
import uuid
from pathlib import Path
from typing import Any, Callable, Optional

from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------------------------
# Environment — fully generated, no hardcoded domains
# ---------------------------------------------------------------------------


class PersonaTemplate(BaseModel):
    """A participant in the simulated workflow (customer, agent, manager, …)."""

    role: str
    background: str
    personality_traits: list[str] = Field(default_factory=list)
    goals: list[str] = Field(default_factory=list)
    default_frustration: float = Field(ge=0.0, le=1.0, default=0.3)


class ToolSpec(BaseModel):
    """A tool the agent-under-test can call — matches openvibe's ToolDefinition shape."""

    model_config = ConfigDict(arbitrary_types_allowed=True)

    name: str
    description: str
    parameters: dict[str, Any] = Field(
        default_factory=lambda: {"type": "object", "properties": {}, "required": []}
    )
    # Real callable — excluded from serialization so datasets remain portable JSON.
    # When set, WorldSimulator invokes this instead of generating a synthetic result.
    callable: Optional[Callable[..., Any]] = Field(default=None, exclude=True)


class EvaluationCriterion(BaseModel):
    """One scoring axis. Weights across all criteria must sum to 1.0."""

    name: str
    description: str
    weight: float = Field(ge=0.0, le=1.0)
    rubric: dict[str, str] = Field(
        description="Score bucket → description. E.g. '0.0-0.4': 'Poor: …'",
        default_factory=dict,
    )


class SimEnvironment(BaseModel):
    """A fully LLM-generated simulation environment.

    Replaces the old hardcoded domain files entirely.  Generated by
    :class:`~openvibe.sim.designer.SimDesigner` from any plain-text context.
    """

    name: str
    description: str
    context: str  # original context string used for design

    personas: list[PersonaTemplate]
    tools: list[ToolSpec]
    evaluation_criteria: list[EvaluationCriterion]
    constraints: list[str] = Field(default_factory=list)
    workflow_rules: list[str] = Field(default_factory=list)
    agent_system_prompt: str

    # Free-text hint — not an enum, user can describe anything
    domain_hint: str = ""
    created_at: float = Field(default_factory=time.time)


# ---------------------------------------------------------------------------
# Scenario
# ---------------------------------------------------------------------------


class Difficulty(str):
    """Free-text difficulty label generated by the designer (e.g. 'easy', 'adversarial')."""

    pass


class OutcomeStatus(str):
    RESOLVED = "resolved"
    ESCALATED = "escalated"
    ABANDONED = "abandoned"
    PENDING = "pending"


class Turn(BaseModel):
    role: str  # matches a persona role or "agent" / "system"
    content: str
    timestamp: float = Field(default_factory=time.time)
    metadata: dict[str, Any] = Field(default_factory=dict)


class ScenarioMetadata(BaseModel):
    scenario_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    difficulty: str = "medium"  # free-text, LLM-assigned
    tags: list[str] = Field(default_factory=list)
    generated: bool = False
    created_at: float = Field(default_factory=time.time)
    version: str = "1.0"


class Scenario(BaseModel):
    """One enterprise workflow scenario with full evaluation spec."""

    metadata: ScenarioMetadata

    title: str
    description: str

    # Agent instructions (from SimEnvironment, possibly scenario-tailored)
    system_prompt: str

    # Seed context for the simulation
    initial_context: dict[str, Any] = Field(default_factory=dict)

    # Opening turn(s) — world.py extends this during simulation
    turns: list[Turn] = Field(default_factory=list)

    # Which persona template drives this scenario
    primary_persona_role: str = ""

    # Evaluation
    expected_outcome: str = OutcomeStatus.RESOLVED  # free-text
    evaluation_criteria: list[EvaluationCriterion] = Field(default_factory=list)
    constraints: list[str] = Field(default_factory=list)

    def to_jsonl_line(self) -> str:
        return self.model_dump_json()

    @classmethod
    def from_jsonl_line(cls, line: str) -> "Scenario":
        return cls.model_validate_json(line)


# ---------------------------------------------------------------------------
# Simulation result
# ---------------------------------------------------------------------------


class SimulationResult(BaseModel):
    scenario_id: str
    agent_turns: list[Turn] = Field(default_factory=list)
    full_conversation: list[Turn] = Field(default_factory=list)
    actual_outcome: str = OutcomeStatus.PENDING
    steps_taken: int = 0
    elapsed_ms: int = 0
    aborted: bool = False
    error: Optional[str] = None


# ---------------------------------------------------------------------------
# Evaluation result
# ---------------------------------------------------------------------------


class CriterionScore(BaseModel):
    criterion: str
    score: float = Field(ge=0.0, le=1.0)
    weighted_score: float
    rationale: str


class EvaluationResult(BaseModel):
    scenario_id: str
    scenario_title: str
    difficulty: str
    agent_name: str
    model: str
    criterion_scores: list[CriterionScore]
    total_score: float
    outcome_match: bool
    feedback: str
    improvement_suggestions: list[str] = Field(default_factory=list)
    elapsed_ms: int = 0


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------


class DatasetMetadata(BaseModel):
    name: str
    description: str = ""
    context: str = ""  # the original context string
    environment: Optional[SimEnvironment] = None  # embedded for full portability
    created_at: float = Field(default_factory=time.time)
    designer_model: str = ""
    tags: list[str] = Field(default_factory=list)
    version: str = "1.0"


class Dataset(BaseModel):
    metadata: DatasetMetadata
    scenarios: list[Scenario] = Field(default_factory=list)

    def save(self, path: str | Path) -> None:
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        with open(p, "w", encoding="utf-8") as f:
            f.write(self.metadata.model_dump_json() + "\n")
            for s in self.scenarios:
                f.write(s.to_jsonl_line() + "\n")

    @classmethod
    def load(cls, path: str | Path) -> "Dataset":
        lines = [l for l in Path(path).read_text(encoding="utf-8").splitlines() if l.strip()]
        metadata = DatasetMetadata.model_validate_json(lines[0])
        scenarios = [Scenario.from_jsonl_line(l) for l in lines[1:]]
        return cls(metadata=metadata, scenarios=scenarios)

    def to_jsonl(self) -> str:
        lines = [self.metadata.model_dump_json()]
        lines.extend(s.to_jsonl_line() for s in self.scenarios)
        return "\n".join(lines)

    def summary(self) -> dict[str, Any]:
        by_diff: dict[str, int] = {}
        for s in self.scenarios:
            k = s.metadata.difficulty
            by_diff[k] = by_diff.get(k, 0) + 1
        return {
            "name": self.metadata.name,
            "total": len(self.scenarios),
            "by_difficulty": by_diff,
            "generated": sum(1 for s in self.scenarios if s.metadata.generated),
        }


# ---------------------------------------------------------------------------
# Aggregate evaluation report
# ---------------------------------------------------------------------------


class EvaluationReport(BaseModel):
    dataset_name: str
    context: str
    total_scenarios: int
    evaluated: int
    mean_total_score: float
    median_total_score: float
    pass_rate: float  # fraction >= 0.7
    by_difficulty: dict[str, float]
    by_criterion: dict[str, float]
    outcome_accuracy: float
    results: list[EvaluationResult]
    generated_at: float = Field(default_factory=time.time)

    @classmethod
    def from_results(
        cls,
        results: list[EvaluationResult],
        dataset: Dataset,
    ) -> "EvaluationReport":
        scores = [r.total_score for r in results]
        mean_score = statistics.mean(scores) if scores else 0.0
        median_score = statistics.median(scores) if scores else 0.0
        pass_rate = sum(1 for s in scores if s >= 0.7) / len(scores) if scores else 0.0
        outcome_acc = (
            sum(1 for r in results if r.outcome_match) / len(results) if results else 0.0
        )
        by_diff: dict[str, list[float]] = {}
        for r in results:
            by_diff.setdefault(r.difficulty, []).append(r.total_score)
        by_crit: dict[str, list[float]] = {}
        for r in results:
            for cs in r.criterion_scores:
                by_crit.setdefault(cs.criterion, []).append(cs.score)

        return cls(
            dataset_name=dataset.metadata.name,
            context=dataset.metadata.context,
            total_scenarios=len(dataset.scenarios),
            evaluated=len(results),
            mean_total_score=mean_score,
            median_total_score=median_score,
            pass_rate=pass_rate,
            by_difficulty={k: statistics.mean(v) for k, v in by_diff.items()},
            by_criterion={k: statistics.mean(v) for k, v in by_crit.items()},
            outcome_accuracy=outcome_acc,
            results=results,
        )

    def to_markdown(self) -> str:
        lines = [
            f"# Evaluation Report: {self.dataset_name}",
            f"",
            f"**Context:** {self.context[:120]}{'…' if len(self.context) > 120 else ''}",
            f"**Scenarios:** {self.total_scenarios} | **Evaluated:** {self.evaluated}",
            f"",
            f"## Summary",
            f"",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Mean Score | {self.mean_total_score:.3f} |",
            f"| Median Score | {self.median_total_score:.3f} |",
            f"| Pass Rate (≥0.7) | {self.pass_rate:.1%} |",
            f"| Outcome Accuracy | {self.outcome_accuracy:.1%} |",
            f"",
            f"## By Difficulty",
            f"",
        ]
        for diff, score in sorted(self.by_difficulty.items()):
            lines.append(f"- **{diff}**: {score:.3f}")
        lines += ["", "## By Criterion", ""]
        for crit, score in sorted(self.by_criterion.items(), key=lambda x: -x[1]):
            lines.append(f"- **{crit}**: {score:.3f}")
        lines += ["", "## Individual Results", ""]
        for r in sorted(self.results, key=lambda x: -x.total_score):
            icon = "✓" if r.total_score >= 0.7 else "✗"
            lines.append(f"- {icon} **{r.scenario_title}** ({r.difficulty}) — {r.total_score:.3f}")
        return "\n".join(lines)

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump()
